 --DATA DEFINITION LANGUAGE (DDL)
-- THEY ARE USED TO DEFINE SQL OBJECTS 
-- OBJECTS INCLUDE ==> DATABASE, SCHEMA, TABLE 

 --CREATE
CREATE DATABASE NEW_JERSEY;

-- TO INITIATE THE DATABASE, WE USE THE ===> USE DATABASE SYNTAX 
 USE NEW_JERSEY;

-- CREATE TABLE IN SQL 

-- 01. WE USE THE SYNTAX ==> CREATE TABLE /TABLENAME/
-- 02. WE INSERT THE COLUMNS WITHIN A BRACKET AFTER THE TABLE 
-- 03. WE DEFINE THE DATATYPES FOR EACH COLUMN 
-- 04. WE DEFINE THE CONSTRAINTS 
-- CONSTRAINTS: LAWS GOVERNING A COLUMN ==> NOT NULL, UNIQUE, PRIMARY KEY
-- 05. WE DEFINE THE AUTO INCREMEMT COLUMN FOR THE PRIMARY KEY COLUMN (OPTIONAL)
-- AUTO INCREMENT / IDENTITY  TAKES TWO VALUES IN ITS BRACKETS 
-- THE FIRST IS THE STARATING POINT 
-- THE SECOND IS THE INCREMENT VALUE 
-- FOR EXAMPLE 
-- AUTO INCREMENT (1,1) ==> 1,2,3


-- LETS CREATE A TABLE FOR A BANK, 
-- TABLENAME ==> CUSTOMER_INFO
-- COLUMNS ==> CUSTOMER_ID, FIRSTNAME, LASTNAME, ACCOUNT_NUMBER 

CREATE TABLE CUSTOMER_INFO(
	CUSTOMER_ID INT PRIMARY KEY IDENTITY(1,1),
	FIRSTNAME VARCHAR(50) NOT NULL,
	LASTNAME VARCHAR(50) NOT NULL,
	ACCOUNT_NUMBER CHAR(10) UNIQUE NOT NULL
	);

-- A customer's first name, last name, email, sign-up  date, and number of minutes spent on the dvd rental  site. 
-- You should also have some sort of id tracker for  them. You have free reign on how you want to create  this table

-- DATE - format YYYY-MM-DD
-- DATETIME - format: YYYY-MM-DD HH:MI:SS
-- TIME 

-- DAY 04
USE NEW_JERSEY;
-- ALTER
-- USED TO ADD, DELETE OR MODIFY COLUMNS IN AN EXISTING TABLE 

-- TO ADD TO A TABLE 
-- LET US ADD THE ADDRESS COLUMN TO OUR CUSTOMER_INFO TABLE 
ALTER TABLE CUSTOMER_INFO
ADD ADDRESS VARCHAR(50);

-- TO DELETE A COLUMN FROM A TABLE 
-- LET US DELETE THE ADDRESS COLUMN FROM OUR CUSTOMER_INFO TABLE 
ALTER TABLE CUSTOMER_INFO 
DROP COLUMN ADDRESS;
 
-- TO MODIFY A COLUMN
-- USED TO ALTER THE DATATYPE OF A COLUMN IN A TABLE
-- IN MSSQL
ALTER TABLE CUSTOMER_INFO
ALTER COLUMN ADDRESS CHAR(50);

-- IN MYSQL/ORACLE 
ALTER TABLE CUSTOMER_INFO
MODIFY COLUMN ADDRESS CHAR(50);

-- DROP 
-- THIS IS USED TO DROP(DELETE) AN EXISTING TABLE IN A DATABASE
-- IT CAN ALSO BE USED TO DROP(DELETE) A DATABASE

-- TO DROP(DELETE) A DATABASE
DROP DATABASE AdventureWorks2019;

-- TO DROP(DELETE) A TABLE 
DROP TABLE CUSTOMER_INFO;