-- INTERACTING WITH MICROSOFT EXCEL
-- IMPORTING FROM MS EXCEL 

-- TO IMPORT TABLE FROM EXCEL

-- 01 LOCATE THE DATABASE YOU WANT THE TABLE TO BE 
-- 02 RIGHT CLICK ON THE DATAABASE AND CHOSETASK 
-- 03 TASK ==> IMPORT FLAT FILES 

-- To import 
use NEW_JERSEY
select * from furniture;

-- EXPORTING TO MS EXCEL 
-- select product name and product color and price 

SELECT PRODUCT, PRODUCT_COLOR, PRODUCT_PRICE FROM FURNITURE;